#ifndef _MINER_H_
#define _MINER_H_

#include "serial.h"

#define HW_STATISTIC_FEATURE
#undef MUTEX_SWITCH_FEATURE
#undef STATISTIC_SYSTEM_FEATURE
#undef SOCKET_API_FEAUTRE
#undef LOG_SYSTEM_FEATURE

#define MAX_ASICS_OF_CHAIN  24

#define MAX_CHAIN_NUM   MAX_UART_NUM
#define MAX_PWM_CHANNEL 2

#define MAX_POOL_NUM    2

/*i2c configuration*/
#define I2C_MASTER_INDEX_OF_CONTROLBOARD_0  0
#define I2C_MASTER_INDEX_OF_HASHBOARD_0     0
#define I2C_MASTER_INDEX_OF_DISPLAY         0

#define I2C_MASTER_INDEX_OF_HASHBOARD_1     1
#define I2C_MASTER_INDEX_OF_POWER           1

/*CRITICAL CONFIGURATION.*/

#define UART_CHAIN_0_TXD0       CONFIG_GPIO_UART_CHAIN_0_TXD0
#define UART_CHAIN_0_RXD0       CONFIG_GPIO_UART_CHAIN_0_RXD0
#define GPIO_RESET_CHAIN_0      CONFIG_GPIO_RESET_PIN_0

#define UART_CHAIN_1_TXD1       CONFIG_GPIO_UART_CHAIN_0_TXD1
#define UART_CHAIN_1_RXD1       CONFIG_GPIO_UART_CHAIN_0_RXD1
#define GPIO_RESET_CHAIN_1      CONFIG_GPIO_RESET_PIN_1

#define GPIO_IP_REPORTER        CONFIG_GPIO_IP_GET

#define GPIO_HASHBOARD_3V3_CTRL CONFIG_GPIO_HASHBOARD_3V3_CTRL


extern void volc_delay(int ms);

#endif
