#include "themes.h"

// autogenerated, do not modify!
#ifdef __cplusplus
extern "C" {
#endif

#if MINER_THEME == MINER_THEME_HAMMER
#if APP_SUPPORT_FOUND_BLOCK
#include "./hammer/export/btcscreen1.c"
#else
#include "./hammer/export/btcscreen.c"
#endif
#include "./hammer/export/globalStats.c"
#include "./hammer/export/initscreen2.c"
#include "./hammer/export/miningscreen2.c"
#include "./hammer/export/portalscreen.c"
#include "./hammer/export/settingsscreen.c"
#include "./hammer/export/splashscreen2.c"
#include "./hammer/export/doge.c"
#include "./hammer/export/lite.c"
#include "./hammer/export/wifi1.c"
#include "./hammer/export/wifi2.c"
#include "./hammer/export/wifi3.c"
#include "./hammer/export/wifi4.c"
#include "./hammer/export/found.c"
#else
#include "./Jingle/export/btcscreen.c"
#include "./Jingle/export/globalStats.c"
#include "./Jingle/export/initscreen2.c"
#include "./Jingle/export/miningscreen2.c"
#include "./Jingle/export/portalscreen.c"
#include "./Jingle/export/settingsscreen.c"
#include "./Jingle/export/splashscreen2.c"
#endif

#ifdef __cplusplus
}
#endif
